Adding better icon and text for "Actions" of a stopped journey
laudspeaker/laudspeaker pull request #132
Opened 2023-04-06 03:59 UTC by rsverma007

Fixes #126 
- Adds a different icon to show it's not editable.
- Changes text to "View" in dropdown menu
Screenshot of new icon + "View" text:
<img width="1179" alt="Screen Shot 2023-04-05 at 4 06 39 PM" src="https://user-images.githubusercontent.com/129563453/230268438-dcbf5f02-2825-4c10-878a-99c5c9815299.png">

2023-04-06 03:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/laudspeaker/laudspeaker?pullRequest=132) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/laudspeaker/laudspeaker?pullRequest=132) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/laudspeaker/laudspeaker?pullRequest=132) it.</sub>

2023-04-11 20:13 UTC, mcharawi requested changes
Overall looks good, some minor feedback.

2023-04-11 20:13 UTC, mcharawi commented on packages/client/src/components/TableTemplate/TableTemplate.tsx
> +            {row.isStopped ? (
This should be either active or stopped, since currently active campaigns are also not editable.

2023-04-11 20:13 UTC, mcharawi commented on packages/client/src/components/TableTemplate/TableTemplate.tsx
> +                    {row.isStopped ? "View" : "Edit"}
Either active or stopped.

2023-04-15 19:52 UTC, rohitverma007 commented on packages/client/src/components/TableTemplate/TableTemplate.tsx
> +            {row.isStopped ? (
Updated!

2023-04-15 19:52 UTC, rohitverma007 commented on packages/client/src/components/TableTemplate/TableTemplate.tsx
> +                    {row.isStopped ? "View" : "Edit"}
Updated!

2023-04-16 23:08 UTC, merged